// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SearchFormController from "./search_form_controller.js"
application.register("search-form", SearchFormController)

import GroupSpendingChartController from "./group_spending_chart_controller.js"
application.register("group-spending-chart", GroupSpendingChartController)

import GroupSpendingSparklineController from "./group_spending_sparkline_controller.js"
application.register("group-spending-sparkline", GroupSpendingSparklineController)
