# frozen_string_literal: true

# Serves the OpenAPI description generated by the rswag specs, for the docs UI and for
# AI clients discovering the API. Any signed-in user or token may read it.
class OpenapiController < ApplicationController
  SPEC_PATH = Rails.root.join('swagger/v1/swagger.yaml')

  skip_authorization_check

  def show
    respond_to do |format|
      format.json { render json: YAML.safe_load_file(SPEC_PATH) }
    end
  end
end
